### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Behkar** [zyedidia/multiplix#1]
I get a strange error while compiling:

`‍‍
→ knit board=virt_riscv64`
The result was:

`[1/9] .bootobj/bootloader.o`

`[2/9] .bootobj/libd/libc.o`

`[3/9] .bootobj/bootloader/main-payload.o`

`[4/9] .kobj/kernel.o`

`[5/9] .kobj/libd/libc.o`

`[6/9] kernel.elf`

`/home/mahdis/gnu-riscv64-unknown-elf-linux-amd64/gnu-riscv64-unknown-elf/bin/../lib/gcc/riscv64-unknown-elf/13.0.1/../../../../riscv64-unknown-elf/bin/ld: warning: kernel.elf has a LOAD segment with RWX permissions`

`[7/9] kernel.payload`

`/usr/bin/sh: line 1: plboot: command not found
removing 'kernel.payload' due to failure
Knitfile: 'kernel.payload': error during recipe: exit status 127`

I also get the same error with the ‍`knit dc=gdc` command.

My OS version is Fedora 37

**Comment by Behkar** [comment]
I'm not familiar with the knit compile system, where is the log stored?

**Comment by zyedidia** [comment]
Thanks for opening the issue. `plboot` is a custom tool in the `tools` directory that you must install first (it is used to create the kernel payload for the boot loader, and for sending a kernel payload over UART if using actual hardware). Run `go install` from inside `tools/plboot` (or use `go build` and install the binary where ever you want).

If you want to see the exact commands that knit runs, use `knit -s basic` (to use the basic output style).

**Comment by Behkar** [comment]
Thank you, it worked.
