### ISSUE TITLE
Move Queue code?

### ISSUE THREAD

**Issue by wilsonk** [zyedidia/multiplix#2]
Just looking around and noticed that 'struct Queue' is in schedule.d, but wondered if perhaps it should be move to it's own file in lib/core like Vector.d (etc.)? Just a thought.  Great project, btw.

**Comment by zyedidia** [comment]
I think the queue's linked list could be factored out into a generic version in lib/core if/when there's another use for it, but currently the queue in schedule is specifically a wait queue at least the specific things such as operations for waking processes should remain there. Thanks for taking a look!

**Comment by wilsonk** [comment]
Ah, I see the queue is specialized for that location in schedule.d and only used in proc.d now. I just did a quick search for Lists, Queues or other data structures after seeing the vector.d addition, and didn't see anything except the Queue :)  I will keep poking around. Thanks
